# Generated by Django 4.0.4 on 2022-05-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0007_meetup_alder_meetup_materialer'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
