# Generated by Django 4.0.4 on 2022-05-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0008_meetup_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetup',
            name='link',
        ),
    ]
